/* Creación de usuario en BD Oracle Cloud */
CREATE USER MDY3131_E1 IDENTIFIED BY "MDY3131.evaluacion01"
  DEFAULT TABLESPACE "DATA"
  TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY3131_E1 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO MDY3131_E1;
GRANT "RESOURCE" TO MDY3131_E1;
ALTER USER MDY3131_E1 DEFAULT ROLE "RESOURCE";